export const isLocalhostHostname = (): boolean => {
  const { hostname } = window.location;

  return (
    hostname === "localhost" ||
    hostname === "127.0.0.1" ||
    hostname === "[::1]" ||
    hostname.endsWith(".localhost")
  );
};

/**
 * Generates a unique, reproducible CSS selector for a given HTMLElement.
 * Priority: ID (for brevity) > Tag Name + nth-of-type (for uniqueness).
 * @param el - The target HTMLElement to generate a selector for.
 * @returns A unique CSS selector string.
 */
export function generateSelector(el: HTMLElement | null): string {
  if (!el) return "";

  const path: string[] = [];
  let current: HTMLElement | null = el;

  while (current && current.nodeType === Node.ELEMENT_NODE) {
    let selector: string = current.nodeName.toLowerCase();

    // 1. If the element has a unique ID, use it and stop.
    // IDs are technically unique per page and offer the most resilient selector.
    if (current.id) {
      selector = `#${CSS.escape(current.id)}`;
      path.unshift(selector);
      break;
    }

    // 2. Calculate the nth-of-type index.
    // We iterate through previous siblings to find how many share the same tag name.
    let index: number = 1;
    let sibling: Element | null = current.previousElementSibling;

    while (sibling) {
      if (sibling.nodeName === current.nodeName) {
        index++;
      }
      sibling = sibling.previousElementSibling;
    }

    selector += `:nth-of-type(${index})`;
    path.unshift(selector);

    // 3. Move up to the parent element.
    current = current.parentElement;
  }

  return path.join(" > ");
}

/**
 * Re-selects an element using the generated selector string.
 * * @param selector - The CSS selector string generated by generateSelector.
 * @param scope - The search root, defaults to document.
 * @returns The HTMLElement if found, otherwise null.
 */
export function selectElement(
  selector: string,
  scope: Document | HTMLElement = document
): HTMLElement | null {
  if (!selector.trim()) return null;

  try {
    return scope.querySelector<HTMLElement>(selector);
  } catch (error) {
    console.error(`Invalid selector: ${selector}`, error);
    return null;
  }
}
